### ISSUE TITLE
emf shop menu - items broken

### ISSUE THREAD

**Issue by Souperhero** [Oheers/EvenMoreFish#104]
version 1.4.4
mc version 1.17.1

clicking either item to sell or sell all breaks and gives me the item.

Attached image
![2022-01-19_17 36 55](https://user-images.githubusercontent.com/10240783/150229708-1af44d9c-d91d-4107-ac42-1f1b9cb692df.png)

[latest.log](https://pastebin.com/vKkBwYVK)

**Comment by Oheers** [comment]
Hi there, sorry I managed to miss your issue. This looks like it's caused by a conflict with another plugin, Would you mind either sending your plugin list here or opening a private ticket on [the discord server](https://discord.gg/Hb9cj3tNbb) and sending it me there, and we'll try and figure out what's going wrong.

- Oheers :)

**Comment by sarhatabaot** [comment]
Closed for inactivity. If this issue wasn't fixed, open another issue or reopen this one.
