### ISSUE TITLE
error console

### ISSUE THREAD

**Issue by Aides123** [Oheers/EvenMoreFish#105]
https://pastebin.com/6W0qm43f

**Comment by Oheers** [comment]
Hi there, this is due to the player being kicked before the plugin could start working out what to do, but also after the fish event had been sent to the plugin. It's completely fine to ignore this message and I'll prevent it from being sent in the upcoming version, thank you very much for reporting it however, it is appreciated. :)

Oheers

**Comment by sarhatabaot** [comment]
Possibly implemented already.
