### ISSUE TITLE
Option to disable update checker & login notification.

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#160]
Would it be possible to add an option to disable the update checker and login notification for those with wildcard permissions?

**Comment by Oheers** [comment]
This comes with the `emf.admin` permission which grants users access to start competitions, give themselves fish, baits and future rather important commands - I'd rather keep this in as I can't be 100% certain there won't ever be future security updates to the plugin which server admins need to be aware of.

Thank you for taking your time to make the suggestion though, if it's suggested a few more times I'll add it to the todo list by popular request. Have a nice day :)

**Comment by Oheers** [comment]
Oh right I see, it shouldn't really be checking against updates from the dev builds but I'll add it as a task on the todo list :)

**Comment by Mike5357** [comment]
Even if there was a specific permission node that was needed to disable update check notifications instead of a config setting, any way of being able to disable the message on login is welcome! I've managed to disable the flood of version checks I receive on login from every other plugin of ours except for this one
