### ISSUE TITLE
Displayname doesn't work

### ISSUE THREAD

**Issue by RoVaSte** [Oheers/EvenMoreFish#243]
I am trying to use the  "displayname:" in fish.yml, but the fish doesn't get renamed. Please fix!

**Comment by RoVaSte** [comment]
anyone?

**Comment by Oheers** [comment]
Hi there, incredibly sorry about the delay. Over the next two weeks when I'll have a bit of free time I'm going to try and collate togerther the biggest bugs with the plugin and get the plugin back into a working state. I've been very busy with studies and am aware EMF has been put onto the backburner massively which has been less than ideal for a lot of servers and many more players. I'm going to post a spigot update of where the current codebase of the plugin's at since there's been some work done by some really great contributors but hasn't been posted to the official spigot site yet - whichever bugs still exist on that version I'll try to tackle.
