### ISSUE TITLE
Interact event fire twice

### ISSUE THREAD

**Issue by exzolink** [Oheers/EvenMoreFish#68]
Hi! i using command with interact event and its fires twice on use
Also did you fixed bug with placing heads?

**Comment by Oheers** [comment]
The latest version (1.3.3) fixes the interact-event issue, you can get it from the Spigot page under the version "1.3.3.1" because I needed to fix a small bug with releasing 1.3.3.

The issue with placing heads is in the priority 1 section on my todo list and will be in the next update, thank you for waiting this long :)
